### ISSUE TITLE
12月15号之后就不行了。。。

### ISSUE THREAD

**Issue by pengleichen** [jinboyigu/lazy_script#12]

**Comment by jinboyigu** [comment]
??? 什么不行了

**Comment by pengleichen** [comment]
好像是最近京东Cookie三五天就要更新下，不知道为什么，之前都是解决一个月呢，你又遇到吗？还是我搞的不对。
另外请教一下如何配置发送通知的Secrets Key

**Comment by pengleichen** [comment]
好像是最近京东Cookie三五天就要更新下，不知道为什么，之前都是解决一个月呢，你又遇到吗？还是我搞的不对。
另外请教一下如何配置发送通知的Secrets Key, 谢谢

**Comment by pengleichen** [comment]
好像是最近京东Cookie三五天就要更新下，不知道为什么，之前都是接近一个月呢，不知道为什么。
另外请教一下如何配置发送通知的Secrets Key, 谢谢

**Comment by jinboyigu** [comment]
我是通过 https://m.jd.com 登录活动Cookie的, 还是一个月有效.

**Comment by jinboyigu** [comment]
- ServerChan 配置的可以看 https://sct.ftqq.com
  获取sendKey就可以了
- 邮件是用了  https://github.com/nodemailer/nodemailer
   大概是 {"auth":{"user":"user","pass":"pass"},"host":"host","port":port,"secure":true}
