### ISSUE TITLE
邮件通知如何设置

### ISSUE THREAD

**Issue by wheatwee** [jinboyigu/lazy_script#14]
请教一下，想要邮件通知，是设置MAILER_TRANSPORTER_OPTION吗？这个值的格式是什么样的呢？

另外not_run想设置多个脚本不跑，值的格式是什么样的呢？

**Comment by jinboyigu** [comment]
`MAILER_TRANSPORTER_OPTION` 的格式大致如下, 具体可参考 https://nodemailer.com/about
`
{
    "auth": {
      "user": "$user",
      "pass": "$pass"
    },
    "host": "$host",
    "port": $port,
    "secure": true
  }
`

`not_run` 目前只支持整体停止, 单个脚本不执行可配置 `JD_COOKIE_CONFIG`, 格式大概如下
`
"$pet_key": {
      "scriptName": {
        "disable": [
          "$scriptName"
        ]
      }
    }
`

**Comment by wheatwee** [comment]
感谢解答！我试试看
-------- 原始信息 --------发件人： jyhuang ***@***.***> 日期: 2022/5/16  15:29  (GMT+08:00) 收件人： jinboyigu/lazy_script ***@***.***> 抄送： wheatwee ***@***.***>, Author ***@***.***> 主题： Re: [jinboyigu/lazy_script] 邮件通知如何设置 (Issue #14) 

MAILER_TRANSPORTER_OPTION 的格式大致如下, 具体可参考 https://nodemailer.com/about

{ "auth": { "user": "$user", "pass": "$pass" }, "host": "$host", "port": $port, "secure": true }

not_run 目前只支持整体停止, 单个脚本不执行可配置 JD_COOKIE_CONFIG, 格式大概如下

"$pet_key": { "scriptName": { "disable": [ "$scriptName" ] } }

**Comment by wheatwee** [comment]
感谢回复！邮件通知已设置成功
