### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by zhifeng456** [jinboyigu/lazy_script#4]
Hi,
  大佬你好，我想移植到本地的win10上。
做了一番改造后，request.log 里打印没有登录，没找到入口，大佬能帮忙看下吗？谢谢。

16:18:32 [jdAPI] [success] {"resultCode":3,"resultMsg":"请先登陆您的京东账号","resultData":null}
16:24:49 [jdAPI] [success] {"sceneval":2}
16:24:49 [jdAPI] [success] undefined
16:24:49 [jdAPI] [success] {"data":{},"errMsg":"user not login","retCode":30000}
16:24:50 [jdAPI] [success] {"uri":"https://nu.jr.jd.com/gw/generic/jrm/h5/m/process"}
16:24:50 [jdAPI] [success] {"reqData":"{\"actCode\":\"F68B2C3E71\",\"type\":4,\"frontParam\":{\"belong\":\"xianjin\"},\"riskDeviceParam\":\"{\\\"fp\\\":\\\"dfc0f4908b93e9b55f2fc3eb85ec6d21\\\"}\"}"}
16:24:50 [jdAPI] [success] {"resultCode":3,"resultMsg":"请先登陆您的京东账号","resultData":null}
16:25:51 [jdAPI] [success] {"functionId":"swat_game_exchangejingbean"}
16:25:51 [jdAPI] [success] {"body":"{}","appid":"swat_miniprogram"}
16:25:51 [jdAPI] [success] {"code":"5003","msg":"未登录"}

app.log:
16:18:31 [签到集合] [info] [0] {"data":{},"errMsg":"user not login","retCode":30000}
16:24:49 [签到集合] [info] [0] {"data":{},"errMsg":"user not login","retCode":30000}

node log：
> node src/dev.js
Tail starting...
filename: E:\lazy_script\logs/app.log.2021-03-06
encoding: utf-8
fromBeginning: false
filesystem.watch present? true
useWatchFile: false
watch strategy: watch

app.js 运行结果:
......
Unwatch E:\lazy_script\logs/app.log.2021-03-06

**Comment by jinboyigu** [comment]
.env.local 这个文件有配置吗? 这个基本等价于 github action 的secrets

**Comment by zhifeng456** [comment]
.env.local 里的cookie是这样写的，是不是格式啥的不对，导致认证失败了：
key=pt_key=XXXXXX;pt_pin=XXXX

**Comment by jinboyigu** [comment]
`key=value`的格式, key和value都是变量, 比如
`JD_COOKIE=xxxx`
