### ISSUE TITLE
大佬，请帮我看下这是成功了还是失败？为什么没有{ errno: 0, errmsg: 'success', dataset: 'done' }这些

### ISSUE THREAD

**Issue by ufxymsn** [jinboyigu/lazy_script#5]
后面和你的不一样，但也没有出错提示？

Run node src/app.js
  node src/app.js
  shell: /usr/bin/bash -e {0}
  env:
    NODE_ENV: production
    NOT_RUN: 
    SEVER_CHAN_KEY: 
    MAILER_TRANSPORTER_OPTION: 
    JD_FRUIT_WATER_TIMES: 
    JD_COOKIE: ***
    JD_COOKIE_1: ***
    JD_COOKIE_2: ***
    JD_COOKIE_3: 
    JD_COOKIE_4: 
    JD_COOKIE_5: 
    JD_EARN_COOKIE: 
    JD_EARN_COOKIE_1: 
    JD_EARN_COOKIE_2: 
    JD_EARN_COOKIE_3: 
    JD_EARN_COOKIE_4: 
    JD_EARN_COOKIE_5: 
    JD_WQ_COOKIE: 
    JD_WQ_COOKIE_1: 
    JD_WQ_COOKIE_2: 
    JD_WQ_COOKIE_3: 
    JD_WQ_COOKIE_4: 
    JD_WQ_COOKIE_5: 
    JD_APPLET_PIN: 
    JD_APPLET_PIN_1: 
    JD_APPLET_PIN_2: 
    JD_APPLET_PIN_3: 
    JD_APPLET_PIN_4: 
    JD_APPLET_PIN_5: 
    JD_EARN_SHARE_CODE: 
    JD_EARN_SHARE_CODE_1: 
    JD_EARN_SHARE_CODE_2: 
    JD_EARN_SHARE_CODE_3: 
    JD_EARN_SHARE_CODE_4: 
    JD_EARN_SHARE_CODE_5: 
    JD_FRUIT_SHARE_CODE: 
    JD_FRUIT_SHARE_CODE_1: 
    JD_FRUIT_SHARE_CODE_2: 
    JD_FRUIT_SHARE_CODE_3: 
    JD_FRUIT_SHARE_CODE_4: 
    JD_FRUIT_SHARE_CODE_5: 
    JD_PET_SHARE_CODE: 
    JD_PET_SHARE_CODE_1: 
    JD_PET_SHARE_CODE_2: 
    JD_PET_SHARE_CODE_3: 
    JD_PET_SHARE_CODE_4: 
    JD_PET_SHARE_CODE_5: 
    JD_CASH_SHARE_CODE: 
    JD_CASH_SHARE_CODE_1: 
    JD_CASH_SHARE_CODE_2: 
    JD_CASH_SHARE_CODE_3: 
    JD_CASH_SHARE_CODE_4: 
    JD_CASH_SHARE_CODE_5: 
    JD_BEAN_SHARE_CODE: 
    JD_BEAN_SHARE_CODE_1: 
    JD_BEAN_SHARE_CODE_2: 
    JD_BEAN_SHARE_CODE_3: 
    JD_BEAN_SHARE_CODE_4: 
    JD_BEAN_SHARE_CODE_5: 
    JD_WMT_SHARE_CODE: 
    JD_WMT_SHARE_CODE_1: 
    JD_WMT_SHARE_CODE_2: 
    JD_WMT_SHARE_CODE_3: 
    JD_WMT_SHARE_CODE_4: 
    JD_WMT_SHARE_CODE_5: 
    JD_JDFACTORY_SHARE_CODE: 
    JD_JDFACTORY_SHARE_CODE_1: 
    JD_JDFACTORY_SHARE_CODE_2: 
    JD_JDFACTORY_SHARE_CODE_3: 
    JD_JDFACTORY_SHARE_CODE_4: 
    JD_JDFACTORY_SHARE_CODE_5: 
    JD_STALL_SHARE_CODE: 
    JD_STALL_SHARE_CODE_1: 
    JD_STALL_SHARE_CODE_2: 
    JD_STALL_SHARE_CODE_3: 
    JD_STALL_SHARE_CODE_4: 
    JD_STALL_SHARE_CODE_5: 
    JD_STALL_SS: 
    JD_STALL_SS_1: 
    JD_STALL_SS_2: 
    JD_STALL_SS_3: 
    JD_STALL_SS_4: 
    JD_STALL_SS_5: 
    JD_STALL_CRON_SS: 
    JD_STALL_CRON_SS_1: 
    JD_STALL_CRON_SS_2: 
    JD_STALL_CRON_SS_3: 
    JD_STALL_CRON_SS_4: 
    JD_STALL_CRON_SS_5: 
    JD_BC_POSITION_LAT: 
    JD_BC_POSITION_LAT_1: 
    JD_BC_POSITION_LAT_2: 
    JD_BC_POSITION_LAT_3: 
    JD_BC_POSITION_LAT_4: 
    JD_BC_POSITION_LAT_5: 
    JD_BC_POSITION_LNG: 
    JD_BC_POSITION_LNG_1: 
    JD_BC_POSITION_LNG_2: 
    JD_BC_POSITION_LNG_3: 
    JD_BC_POSITION_LNG_4: 
    JD_BC_POSITION_LNG_5: 
    JD_SSJJ_SHARE_CODE: 
    JD_SSJJ_SHARE_CODE_1: 
    JD_SSJJ_SHARE_CODE_2: 
    JD_SSJJ_SHARE_CODE_3: 
    JD_SSJJ_SHARE_CODE_4: 
    JD_SSJJ_SHARE_CODE_5: 
    JD_SSJJ_USER_NAME: 
    JD_SSJJ_USER_NAME_1: 
    JD_SSJJ_USER_NAME_2: 
    JD_SSJJ_USER_NAME_3: 
    JD_SSJJ_USER_NAME_4: 
    JD_SSJJ_USER_NAME_5: 
    JD_DREAMFACTORY_SHARE_CODE: 
    JD_DREAMFACTORY_SHARE_CODE_1: 
    JD_DREAMFACTORY_SHARE_CODE_2: 
    JD_DREAMFACTORY_SHARE_CODE_3: 
    JD_DREAMFACTORY_SHARE_CODE_4: 
    JD_DREAMFACTORY_SHARE_CODE_5: 
    JD_JXCFD_SHARE_CODE: 
    JD_JXCFD_SHARE_CODE_1: 
    JD_JXCFD_SHARE_CODE_2: 
    JD_JXCFD_SHARE_CODE_3: 
    JD_JXCFD_SHARE_CODE_4: 
    JD_JXCFD_SHARE_CODE_5: 
    JD_NIAN_SHARE_CODE: 
    JD_NIAN_SHARE_CODE_1: 
    JD_NIAN_SHARE_CODE_2: 
    JD_NIAN_SHARE_CODE_3: 
    JD_NIAN_SHARE_CODE_4: 
    JD_NIAN_SHARE_CODE_5: 
    JD_BRANDCITY_SHARE_CODE: 
    JD_BRANDCITY_SHARE_CODE_1: 
    JD_BRANDCITY_SHARE_CODE_2: 
    JD_BRANDCITY_SHARE_CODE_3: 
    JD_BRANDCITY_SHARE_CODE_4: 
    JD_BRANDCITY_SHARE_CODE_5: 
    JD_GLOBALCHALLENGE_SHARE_CODE: 
    JD_GLOBALCHALLENGE_SHARE_CODE_1: 
    JD_GLOBALCHALLENGE_SHARE_CODE_2: 
    JD_GLOBALCHALLENGE_SHARE_CODE_3: 
    JD_GLOBALCHALLENGE_SHARE_CODE_4: 
    JD_GLOBALCHALLENGE_SHARE_CODE_5: 
    JD_JXCFD_GROUP_SHARE_CODE: 
    JD_DREAMFACTORY_TUAN_ID: 
    JD_DREAMFACTORY_TUAN_ACTIVE_ID: 
发送成功

**Comment by jinboyigu** [comment]
`{ errno: 0, errmsg: 'success', dataset: 'done' }`是 serverChan的微信推送输出, 具体成不成功看对应脚本有没有执行
