### ISSUE TITLE
请问大佬如何暂停jd_crazy_joy的部分脚本？

### ISSUE THREAD

**Issue by EchoChan314** [jinboyigu/lazy_script#8]
这个合并策略可以参考https://gitee.com/shuye72/MyActions/raw/main/jd_crazy_joy_coin.js
不然无法让收益最大化。

**Comment by jinboyigu** [comment]
代码中已经加了停止自动购买并进行合并的逻辑,  即`JD_CRAZY_JOY_STOP_UPGRADE`

目前来看合并得到的收益几乎没有, 所以先暂停了
