### ISSUE TITLE
原因: Cookie失效‼️

### ISSUE THREAD

**Issue by PLQin** [jinboyigu/lazy_script#9]
【签到概览】:  失败33个
【账号总计】:  获取失败
【其他总计】:  获取失败

京东商城-京豆: 失败, 原因: Cookie失效‼️
京东商城-超市: 失败, 原因: Cookie失效‼️
京东金融-钢镚: 失败, 原因: Cookie失效‼️

---

我是全部失效，很奇怪。可以肯定的是，通过2中方式分别获得cookie测试的，都不行

https://m.jd.com
https://bean.m.jd.com/bean/signIndex.action

**Comment by PLQin** [comment]
哈哈，我成功了，直接取console中的document.cookie不行，去翻他的请求header中的cookie字段，全部copy下来粘贴即可

【签到概览】: 成功19个, 失败17个
【签到奖励】: 20京豆, 0.02钢镚
【其他奖励】: 0.05红包, 0.03金贴, 0.02现金
【账号总计】: 1059京豆, 0.09钢镚
【其他总计】: 0.03金贴, 0.06现金, 0.05红包

**Comment by jinboyigu** [comment]
请求cookie是http-only的, document.cookie是拿不到的.
其实只要pt_key和pt_pin就可以, 可以在浏览器装个 EditThisCookie 插件, 就可以快速找到当前的cookie了
